### ISSUE TITLE
Try to concatenate two files when there is a single cut

### ISSUE THREAD

**Issue by Ichunjo** [begna112/bvsfunc#2]
Example:
```py
import bvsfunc.AudioProcessor as ap
path = r'F:\VPS\ENCO EN COURS\Magia Record\BD\[BDMV][200304][Magia Record][Vol.1]\BD_VIDEO\BDMV\STREAM\00001.m2ts'
ap.VideoSource(infile=path, trimlist="[[None, -48]]", noflac=True, silent=False)
```

The issue is fixed when using a single dict `"[None, -48]"`, though.

**Comment by begna112** [comment]
error example:
```
output_file: F:\VPS\ENCO EN COURS\Magia Record\BD\[BDMV][200304][Magia Record][Vol.1]\BD_VIDEO\BDMV\STREAM\00001_2_temp1.wav already exists and will be overwritten on build
Traceback (most recent call last):
  File "magia_bd01v4.vpy", line 38, in <module>
    ap.VideoSource(infile=path, trimlist="[[None, -24]]", noflac=True, silent=False)
  File "C:\Users\Varde\AppData\Roaming\Python\Python38\site-packages\bvsfunc\AudioProcessor.py", line 203, in VideoSource
    trimfiles, temp_outfiles = trim_tracks_as_wav(extracted_tracks, trimlist, framerate, framenum, silent)
  File "C:\Users\Varde\AppData\Roaming\Python\Python38\site-packages\bvsfunc\AudioProcessor.py", line 87, in trim_tracks_as_wav
    cbn.build(temp_outfiles, outfile, 'concatenate')
  File "C:\Users\Varde\AppData\Roaming\Python\Python38\site-packages\sox\combine.py", line 70, in build
    file_info.validate_input_file_list(input_filepath_list)
  File "C:\Users\Varde\AppData\Roaming\Python\Python38\site-packages\sox\file_info.py", line 238, in validate_input_file_list
    raise ValueError("input_filepath_list must have at least 2 files.")
ValueError: input_filepath_list must have at least 2 files.
```

**Comment by begna112** [comment]
Fixed in https://github.com/begna112/bvsfunc/commit/ffadbf97c168b24bdb5d15d1450319558c53bd94
